import 'package:flutter/material.dart';

import 'models/transport_route.dart';

/// State for transport list data
class TransportListState {
  final List<TransportRoute> routes;
  final List<TransportRoute> filteredRoutes;
  final bool isLoading;
  final bool isLoadingDetails;

  /// When set, only routes whose `agencyName` matches (case-insensitive)
  /// are shown. Seeded from the `operator` query parameter of `/routes`
  /// deep links, and clearable from the UI.
  final String? agencyFilter;

  const TransportListState({
    this.routes = const [],
    this.filteredRoutes = const [],
    this.isLoading = false,
    this.isLoadingDetails = false,
    this.agencyFilter,
  });

  TransportListState copyWith({
    List<TransportRoute>? routes,
    List<TransportRoute>? filteredRoutes,
    bool? isLoading,
    bool? isLoadingDetails,
    String? agencyFilter,
    bool clearAgencyFilter = false,
  }) {
    return TransportListState(
      routes: routes ?? this.routes,
      filteredRoutes: filteredRoutes ?? this.filteredRoutes,
      isLoading: isLoading ?? this.isLoading,
      isLoadingDetails: isLoadingDetails ?? this.isLoadingDetails,
      agencyFilter: clearAgencyFilter
          ? null
          : (agencyFilter ?? this.agencyFilter),
    );
  }
}

/// Provider interface for transport list data.
///
/// Owns shared state plumbing — `_state`, `_notifySafe`, and the
/// canonical `filter` impl — so concrete providers (Otp, Gtfs, …)
/// don't drift on these. Override `filter` only if a feed needs a
/// different match policy.
abstract class TransportListDataProvider extends ChangeNotifier {
  TransportListState _state = const TransportListState(isLoading: true);

  TransportListState get state => _state;

  /// Subclasses set state through this so notifications stay routed
  /// through `_notifySafe`. Direct assignment would skip the dispose
  /// guard.
  @protected
  set state(TransportListState newState) {
    _state = newState;
  }

  bool _disposed = false;

  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }

  /// Notifies listeners on the next frame, so async state updates
  /// don't trigger a setState during a build phase. Subclasses use
  /// this in any async path that mutates `state`.
  @protected
  void notifySafe() {
    if (_disposed) return;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!_disposed) notifyListeners();
    });
  }

  /// Load initial routes
  Future<void> load();

  /// Refresh routes from server
  Future<void> refresh();

  String _query = '';

  /// Filter routes by query.
  ///
  /// Default impl: case-insensitive `contains` match over
  /// `shortName`, `longName`, `headsign`, and `agencyName`.
  /// Notably excludes `name` because some providers (OTP 2.x in
  /// particular) emit autogenerated descriptions there containing
  /// stop-name fragments that match arbitrary substrings.
  ///
  /// The query intersects with [TransportListState.agencyFilter] when
  /// one is active; clearing the query keeps the agency scope.
  void filter(String query) {
    _query = query;
    _applyFilters();
  }

  /// Restrict the list to a single operator/agency, matched
  /// case-insensitively against `agencyName`. Pass null (or an empty
  /// string) to lift the restriction. The active text query keeps
  /// applying within the restricted set.
  void setAgencyFilter(String? agency) {
    final normalized = agency?.trim();
    final cleared = normalized == null || normalized.isEmpty;
    _state = _state.copyWith(
      agencyFilter: cleared ? null : normalized,
      clearAgencyFilter: cleared,
    );
    _applyFilters();
  }

  /// Re-applies the active text query and agency filter to the current
  /// route list. Call after `load`/`refresh`, which reset
  /// `filteredRoutes` to the full list.
  void reapplyFilters() => _applyFilters();

  void _applyFilters() {
    Iterable<TransportRoute> result = _state.routes;

    final agency = _state.agencyFilter?.toLowerCase();
    if (agency != null) {
      result = result.where(
        (route) => (route.agencyName ?? '').trim().toLowerCase() == agency,
      );
    }

    if (_query.isNotEmpty) {
      final lowerQuery = _query.toLowerCase();
      final matches = result.where((route) {
        final searchText =
            '${route.shortName ?? ''} ${route.longName ?? ''} ${route.headsign ?? ''} ${route.agencyName ?? ''}'
                .toLowerCase();
        return searchText.contains(lowerQuery);
      }).toList();

      // Rank by match quality so short queries stay useful: the route whose
      // short name IS the query (bus "R") must beat the hundreds of routes
      // that merely contain the letter somewhere (#844). Ties keep the
      // original list order (sort is decorated with the index — List.sort
      // is not stable).
      int rank(TransportRoute route) {
        final short = (route.shortName ?? '').trim().toLowerCase();
        if (short == lowerQuery) return 0;
        if (short.startsWith(lowerQuery)) return 1;
        if (short.contains(lowerQuery)) return 2;
        return 3;
      }

      final decorated = matches.asMap().entries.toList()
        ..sort((a, b) {
          final byRank = rank(a.value).compareTo(rank(b.value));
          return byRank != 0 ? byRank : a.key.compareTo(b.key);
        });
      result = decorated.map((e) => e.value);
    }

    _state = _state.copyWith(filteredRoutes: result.toList());
    notifySafe();
  }

  /// Get route details by code
  Future<TransportRouteDetails?> getRouteDetails(String code);
}
