import 'package:flutter/material.dart';

import 'models/transport_route.dart';

/// State for transport list data
class TransportListState {
  final List<TransportRoute> routes;
  final List<TransportRoute> filteredRoutes;
  final bool isLoading;
  final bool isLoadingDetails;

  const TransportListState({
    this.routes = const [],
    this.filteredRoutes = const [],
    this.isLoading = false,
    this.isLoadingDetails = false,
  });

  TransportListState copyWith({
    List<TransportRoute>? routes,
    List<TransportRoute>? filteredRoutes,
    bool? isLoading,
    bool? isLoadingDetails,
  }) {
    return TransportListState(
      routes: routes ?? this.routes,
      filteredRoutes: filteredRoutes ?? this.filteredRoutes,
      isLoading: isLoading ?? this.isLoading,
      isLoadingDetails: isLoadingDetails ?? this.isLoadingDetails,
    );
  }
}

/// Provider interface for transport list data.
///
/// Owns shared state plumbing — `_state`, `_notifySafe`, and the
/// canonical `filter` impl — so concrete providers (Otp, Gtfs, …)
/// don't drift on these. Override `filter` only if a feed needs a
/// different match policy.
abstract class TransportListDataProvider extends ChangeNotifier {
  TransportListState _state = const TransportListState(isLoading: true);

  TransportListState get state => _state;

  /// Subclasses set state through this so notifications stay routed
  /// through `_notifySafe`. Direct assignment would skip the dispose
  /// guard.
  @protected
  set state(TransportListState newState) {
    _state = newState;
  }

  bool _disposed = false;

  @override
  void dispose() {
    _disposed = true;
    super.dispose();
  }

  /// Notifies listeners on the next frame, so async state updates
  /// don't trigger a setState during a build phase. Subclasses use
  /// this in any async path that mutates `state`.
  @protected
  void notifySafe() {
    if (_disposed) return;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!_disposed) notifyListeners();
    });
  }

  /// Load initial routes
  Future<void> load();

  /// Refresh routes from server
  Future<void> refresh();

  /// Filter routes by query.
  ///
  /// Default impl: case-insensitive `contains` match over
  /// `shortName`, `longName`, `headsign`, and `agencyName`.
  /// Notably excludes `name` because some providers (OTP 2.x in
  /// particular) emit autogenerated descriptions there containing
  /// stop-name fragments that match arbitrary substrings.
  void filter(String query) {
    if (query.isEmpty) {
      _state = _state.copyWith(filteredRoutes: _state.routes);
    } else {
      final lowerQuery = query.toLowerCase();
      final filtered = _state.routes.where((route) {
        final searchText =
            '${route.shortName ?? ''} ${route.longName ?? ''} ${route.headsign ?? ''} ${route.agencyName ?? ''}'
                .toLowerCase();
        return searchText.contains(lowerQuery);
      }).toList();
      _state = _state.copyWith(filteredRoutes: filtered);
    }
    notifySafe();
  }

  /// Get route details by code
  Future<TransportRouteDetails?> getRouteDetails(String code);
}
